export enum ROUTE {
  HOME = 'HOME',
  ABOUT = 'ABOUT',
  CONTACT = 'CONTACT',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  DASHBOARD = 'DASHBOARD',
  PROFILE = 'PROFILE',
  EMPLOYEES = 'EMPLOYEES',
}
