name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main # Set this to the branch that you want to deploy from
  pull_request:
    branches:
      - main # Set this to the branch that you want to deploy to preview changes in PRs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install # or use yarn or pnpm if that's what your project uses

    - name: Build Frontend
      run: npx nx build frontend --prod # Replace 'frontend' with your frontend app name if it's different

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/apps/frontend # Replace with the path to your frontend build output
